// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT License.
// See the LICENSE file in the project root for more information.

// This code was generated by a T4 template at 10/05/2020 14:25:21.

namespace System.Refactive.Linq
{
    internal partial class QueryLanguage
    {
        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, Func<TSource1, TSource2, TSource3, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TResult>(source1, source2, source3, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, Func<TSource1, TSource2, TSource3, TSource4, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TResult>(source1, source2, source3, source4, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TResult>(source1, source2, source3, source4, source5, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TResult>(source1, source2, source3, source4, source5, source6, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TResult>(source1, source2, source3, source4, source5, source6, source7, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, IRefObservable<TSource10> source10, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, source10, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, IRefObservable<TSource10> source10, IRefObservable<TSource11> source11, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, source10, source11, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, IRefObservable<TSource10> source10, IRefObservable<TSource11> source11, IRefObservable<TSource12> source12, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, source10, source11, source12, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, IRefObservable<TSource10> source10, IRefObservable<TSource11> source11, IRefObservable<TSource12> source12, IRefObservable<TSource13> source13, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, source10, source11, source12, source13, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, IRefObservable<TSource10> source10, IRefObservable<TSource11> source11, IRefObservable<TSource12> source12, IRefObservable<TSource13> source13, IRefObservable<TSource14> source14, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, source10, source11, source12, source13, source14, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, IRefObservable<TSource10> source10, IRefObservable<TSource11> source11, IRefObservable<TSource12> source12, IRefObservable<TSource13> source13, IRefObservable<TSource14> source14, IRefObservable<TSource15> source15, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, source10, source11, source12, source13, source14, source15, resultSelector);
        }

        public virtual IRefObservable<TResult> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TSource16, TResult>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8, IRefObservable<TSource9> source9, IRefObservable<TSource10> source10, IRefObservable<TSource11> source11, IRefObservable<TSource12> source12, IRefObservable<TSource13> source13, IRefObservable<TSource14> source14, IRefObservable<TSource15> source15, IRefObservable<TSource16> source16, Func<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TSource16, TResult> resultSelector)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, TSource9, TSource10, TSource11, TSource12, TSource13, TSource14, TSource15, TSource16, TResult>(source1, source2, source3, source4, source5, source6, source7, source8, source9, source10, source11, source12, source13, source14, source15, source16, resultSelector);
        }

    }


    internal partial class QueryLanguageEx
    {
        public virtual IRefObservable<(TSource1, TSource2)> Zip<TSource1, TSource2>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2)
        {
            return new Zip<TSource1, TSource2, (TSource1, TSource2)>.Observable(source1, source2, (t1, t2) => (t1, t2));
        }

        public virtual IRefObservable<(TSource1, TSource2, TSource3)> Zip<TSource1, TSource2, TSource3>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3)
        {
            return new Zip<TSource1, TSource2, TSource3, (TSource1, TSource2, TSource3)>(source1, source2, source3, (t1, t2, t3) => (t1, t2, t3));
        }

        public virtual IRefObservable<(TSource1, TSource2, TSource3, TSource4)> Zip<TSource1, TSource2, TSource3, TSource4>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, (TSource1, TSource2, TSource3, TSource4)>(source1, source2, source3, source4, (t1, t2, t3, t4) => (t1, t2, t3, t4));
        }

        public virtual IRefObservable<(TSource1, TSource2, TSource3, TSource4, TSource5)> Zip<TSource1, TSource2, TSource3, TSource4, TSource5>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, (TSource1, TSource2, TSource3, TSource4, TSource5)>(source1, source2, source3, source4, source5, (t1, t2, t3, t4, t5) => (t1, t2, t3, t4, t5));
        }

        public virtual IRefObservable<(TSource1, TSource2, TSource3, TSource4, TSource5, TSource6)> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, (TSource1, TSource2, TSource3, TSource4, TSource5, TSource6)>(source1, source2, source3, source4, source5, source6, (t1, t2, t3, t4, t5, t6) => (t1, t2, t3, t4, t5, t6));
        }

        public virtual IRefObservable<(TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7)> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, (TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7)>(source1, source2, source3, source4, source5, source6, source7, (t1, t2, t3, t4, t5, t6, t7) => (t1, t2, t3, t4, t5, t6, t7));
        }

        public virtual IRefObservable<(TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8)> Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8>(IRefObservable<TSource1> source1, IRefObservable<TSource2> source2, IRefObservable<TSource3> source3, IRefObservable<TSource4> source4, IRefObservable<TSource5> source5, IRefObservable<TSource6> source6, IRefObservable<TSource7> source7, IRefObservable<TSource8> source8)
        {
            return new Zip<TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8, (TSource1, TSource2, TSource3, TSource4, TSource5, TSource6, TSource7, TSource8)>(source1, source2, source3, source4, source5, source6, source7, source8, (t1, t2, t3, t4, t5, t6, t7, t8) => (t1, t2, t3, t4, t5, t6, t7, t8));
        }

    }
}
